spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mysql://localhost:3306/myapp_db"
    username: "my-user"
    password: "my-user-pwd"
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
